name: MUnit Test Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  munit-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven

      - name: Install dependencies and Run Tests
        run: mvn clean test -DskipMuleAgent

      - name: Generate Test Coverage Report
        run: mvn org.mule.tools.maven:munit-maven-plugin:2.3.0:coverage-report

      - name: Archive Test Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: target/site/munit-coverage

      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: target/site/munit-coverage/index.html
          flags: unittests
          fail_ci_if_error: true
